customhost = "demodb.cvt05wxs5fqu.us-east-1.rds.amazonaws.com"
customuser = "francois"
custompass = "Test12345!"
customdb = "francoisdb"
custombucket = "safeequitypartners.com"
customregion = "us-east-1"
