customhost = "miracle.cwaqnyx8uyjt.us-east-2.rds.amazonaws.com"
customuser = "francois"
custompass = "Passw0rd123!"
customdb = "francoisdb"
custombucket = "cf-templates-qo3wxwz9hxw-us-east-1"
customregion = "us-east-1"
